name: Build all driver samples
on:
  workflow_dispatch:

jobs:
  build:
    name: Build driver samples
    strategy:
      fail-fast: false
      matrix:
        #configuration: [Debug, Release]
        configuration: [Release]
        #platform: [x64, arm64]
        platform: [x64]
    runs-on: windows-2025-vs2026
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Install Nuget Packages
        run: nuget restore .\packages.config -PackagesDirectory .\packages\

      - name: Retrieve and build all available solutions
        run: .\Build-Samples.ps1 -Samples USB.* -Verbose
        env:
          WDS_Configuration: ${{ matrix.configuration }}
          WDS_Platform: ${{ matrix.platform }}
          WDS_ReportFileName: _overview.${{ matrix.configuration }}.${{ matrix.platform }}

      - name: Archive build logs and overview build reports
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: logs-${{ matrix.configuration }}-${{ matrix.platform }}
          path: _logs
          
      - name: Show USBView
        run: |
          dir usb*view* -recurse
